//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoYoShadeHub.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CoreLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreLang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HoYoShadeHub.Core.Localization.CoreLang", typeof(CoreLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        /// <summary>
        ///   查找类似 Genshin Impact 的本地化字符串。
        /// </summary>
        public static string Game_GenshinImpact {
            get {
                return ResourceManager.GetString("Game_GenshinImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Honkai Impact 3rd 的本地化字符串。
        /// </summary>
        public static string Game_HonkaiImpact3rd {
            get {
                return ResourceManager.GetString("Game_HonkaiImpact3rd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Honkai: Star Rail 的本地化字符串。
        /// </summary>
        public static string Game_HonkaiStarRail {
            get {
                return ResourceManager.GetString("Game_HonkaiStarRail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Honkai: Nexus Anima 的本地化字符串。
        /// </summary>
        public static string Game_NexusAnima {
            get {
                return ResourceManager.GetString("Game_NexusAnima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Petit Planet 的本地化字符串。
        /// </summary>
        public static string Game_PetitPlanet {
            get {
                return ResourceManager.GetString("Game_PetitPlanet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zenless Zone Zero 的本地化字符串。
        /// </summary>
        public static string Game_ZZZ {
            get {
                return ResourceManager.GetString("Game_ZZZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Beta / Creator Experience Client 的本地化字符串。
        /// </summary>
        public static string GameServer_Beta {
            get {
                return ResourceManager.GetString("GameServer_Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Beta Test / Creator Experience Client 的本地化字符串。
        /// </summary>
        public static string GameServer_BetaPostBeta {
            get {
                return ResourceManager.GetString("GameServer_BetaPostBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pre-Beta Test Client 的本地化字符串。
        /// </summary>
        public static string GameServer_BetaPreBeta {
            get {
                return ResourceManager.GetString("GameServer_BetaPreBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bilibili 的本地化字符串。
        /// </summary>
        public static string GameServer_Bilibili {
            get {
                return ResourceManager.GetString("GameServer_Bilibili", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   查找类似 First Closed Beta Test 的本地化字符串。
        /// </summary>
        public static string GameServer_CBT1 {
            get {
                return ResourceManager.GetString("GameServer_CBT1", resourceCulture);
            }
        }
        
        
        
        
        /// <summary>
        ///   查找类似 China Server 的本地化字符串。
        /// </summary>
        public static string GameServer_ChinaServer {
            get {
                return ResourceManager.GetString("GameServer_ChinaServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CN Beta / Creator Experience Client 的本地化字符串。
        /// </summary>
        public static string GameServer_CNBeta {
            get {
                return ResourceManager.GetString("GameServer_CNBeta", resourceCulture);
            }
        }
        
        
        
        
        /// <summary>
        ///   查找类似 Global Server 的本地化字符串。
        /// </summary>
        public static string GameServer_GlobalServer {
            get {
                return ResourceManager.GetString("GameServer_GlobalServer", resourceCulture);
            }
        }
        
        
        
        
        
        /// <summary>
        ///   查找类似 OS Beta / Creator Experience Client 的本地化字符串。
        /// </summary>
        public static string GameServer_OSBeta {
            get {
                return ResourceManager.GetString("GameServer_OSBeta", resourceCulture);
            }
        }
        
        
        
        
        
        
        /// <summary>
        ///   查找类似 Artifacts 的本地化字符串。
        /// </summary>
        public static string GenshinQueryType_Artifact {
            get {
                return ResourceManager.GetString("GenshinQueryType_Artifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Genesis Crystals 的本地化字符串。
        /// </summary>
        public static string GenshinQueryType_GenesisCrystal {
            get {
                return ResourceManager.GetString("GenshinQueryType_GenesisCrystal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original Resins 的本地化字符串。
        /// </summary>
        public static string GenshinQueryType_OriginalResin {
            get {
                return ResourceManager.GetString("GenshinQueryType_OriginalResin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Primogems 的本地化字符串。
        /// </summary>
        public static string GenshinQueryType_Primogem {
            get {
                return ResourceManager.GetString("GenshinQueryType_Primogem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weapons 的本地化字符串。
        /// </summary>
        public static string GenshinQueryType_Weapon {
            get {
                return ResourceManager.GetString("GenshinQueryType_Weapon", resourceCulture);
            }
        }
        
        
        
        
        /// <summary>
        ///   查找类似 Light Cone 的本地化字符串。
        /// </summary>
        public static string StarRailQueryType_LightCone {
            get {
                return ResourceManager.GetString("StarRailQueryType_LightCone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oneiric Shared 的本地化字符串。
        /// </summary>
        public static string StarRailQueryType_OneiricShared {
            get {
                return ResourceManager.GetString("StarRailQueryType_OneiricShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Relic 的本地化字符串。
        /// </summary>
        public static string StarRailQueryType_Relic {
            get {
                return ResourceManager.GetString("StarRailQueryType_Relic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stellar Jade 的本地化字符串。
        /// </summary>
        public static string StarRailQueryType_StellarJade {
            get {
                return ResourceManager.GetString("StarRailQueryType_StellarJade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trailblaze Power 的本地化字符串。
        /// </summary>
        public static string StarRailQueryType_TrailblazePower {
            get {
                return ResourceManager.GetString("StarRailQueryType_TrailblazePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Battery Charge 的本地化字符串。
        /// </summary>
        public static string ZZZQueryType_BatteryCharge {
            get {
                return ResourceManager.GetString("ZZZQueryType_BatteryCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bundle 的本地化字符串。
        /// </summary>
        public static string ZZZQueryType_Bundle {
            get {
                return ResourceManager.GetString("ZZZQueryType_Bundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drive Disc 的本地化字符串。
        /// </summary>
        public static string ZZZQueryType_DriveDisc {
            get {
                return ResourceManager.GetString("ZZZQueryType_DriveDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monochrome 的本地化字符串。
        /// </summary>
        public static string ZZZQueryType_Monochrome {
            get {
                return ResourceManager.GetString("ZZZQueryType_Monochrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ploychrome 的本地化字符串。
        /// </summary>
        public static string ZZZQueryType_Ploychrome {
            get {
                return ResourceManager.GetString("ZZZQueryType_Ploychrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 W-Engine 的本地化字符串。
        /// </summary>
        public static string ZZZQueryType_WEngine {
            get {
                return ResourceManager.GetString("ZZZQueryType_WEngine", resourceCulture);
            }
        }
    }
}
